//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTest.TestStrings", typeof(TestStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P 11.613591 11.658737 1 34 0
        ///P 1.290286 9.040786 1 365 5
        ///P 21.936895 14.276689 1 224 5
        ///P 5.648358 18.265992 1 345 4
        ///P 17.578824 5.051482 1 220 4
        ///P 0.000000 17.566463 1 97 2
        ///P 23.227182 5.751012 1 223 2
        ///P 15.996407 22.492537 1 275 5
        ///P 7.230774 0.824938 1 345 5
        ///P 12.096861 23.317475 1 212 5
        ///P 11.130321 0.000000 1 182 5
        ///P 5.905729 2.482273 1 80 1
        ///P 17.321452 20.835201 1 159 1
        ///P 18.286013 0.765778 1 235 3
        ///P 4.941168 22.551697 1 317 3
        ///P 20.106711 18.059385 1 412 5
        ///P 3.120471 5.258090 1 158 5
        ///P 4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GameStateEndState1 {
            get {
                return ResourceManager.GetString("GameStateEndState1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P 2 3 1 100 5
        ///P 17 18 2 100 5
        ///P 10 10 0 40 4.
        /// </summary>
        internal static string GameStateNoFleets {
            get {
                return ResourceManager.GetString("GameStateNoFleets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P 2 3 1 100 5
        ///P 17 18 2 100 5
        ///P 10 10 0 40 4
        ///F 1 50 0 1 22 22.
        /// </summary>
        internal static string GameStateOneFleetInsufficient {
            get {
                return ResourceManager.GetString("GameStateOneFleetInsufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P 2 3 1 100 5
        ///P 17 18 2 100 5
        ///P 10 10 0 40 4
        ///F 1 210 0 1 22 22.
        /// </summary>
        internal static string GameStateOneFleetNeutralise {
            get {
                return ResourceManager.GetString("GameStateOneFleetNeutralise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P 2 3 1 100 5
        ///P 17 18 2 100 5
        ///P 10 10 0 40 4
        ///F 1 300 0 1 22 22.
        /// </summary>
        internal static string GameStateOneFleetOverpower {
            get {
                return ResourceManager.GetString("GameStateOneFleetOverpower", resourceCulture);
            }
        }
    }
}
